# Generated by Django 3.1.4 on 2020-12-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(default='img', upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='navf',
            field=models.CharField(default='img', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='navs',
            field=models.CharField(default='img', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='navt',
            field=models.CharField(default='img', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='stext',
            field=models.TextField(default='img'),
        ),
    ]
