# Generated by Django 3.1.4 on 2020-12-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201211_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stitle',
            field=models.CharField(default='img', max_length=300),
        ),
    ]
