# Generated by Django 3.1.4 on 2020-12-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20201211_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='navf',
        ),
        migrations.RemoveField(
            model_name='event',
            name='navs',
        ),
        migrations.RemoveField(
            model_name='event',
            name='navt',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='bg', upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(default='logo', upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stext',
            field=models.TextField(default='No text'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stitle',
            field=models.CharField(default='No Title', max_length=300),
        ),
    ]
